# Makefile for demo programs


all:	pco_camera_grab pco_edge_grab pco_edge_grab_gs pco_ser_con


clean:	FORCE
	cd ./pco_camera_grab && $(MAKE) clean
	cd ./pco_edge_grab && $(MAKE) clean
	cd ./pco_edge_grab_gs && $(MAKE) clean
	cd ./pco_ser_con && $(MAKE) clean


pco_camera_grab: FORCE
	cd ./pco_camera_grab && $(MAKE)

pco_edge_grab: FORCE
	cd ./pco_edge_grab && $(MAKE)

pco_edge_grab_gs: FORCE
	cd ./pco_edge_grab_gs && $(MAKE)

pco_ser_con: FORCE
	cd ./pco_ser_con && $(MAKE)


FORCE:
