/*
 * sisoboards.h
 *
 * Copyright (c) 2009 Silicon Software GmbH, All Rights Reserved. 
 */

/**
 * \file sisoboards.h
 *
 * \brief Board type constant definitions.
 *
 * \author Silicon Software GmbH
 */

#ifndef _SISOBOARDS_H
#define _SISOBOARDS_H

enum siso_board_type {
	PN_MICROENABLE = 0xa1,
	PN_MICROENABLEII = 0xa2,
	PN_MICROENABLE3I = 0xa3,
	PN_MICROENABLE3IXXL = 0xa31,
	PN_MICROENABLE4AD1CL = 0xa40,
	PN_MICROENABLE4BASE = PN_MICROENABLE4AD1CL,
	PN_MICROENABLE4BASEx4 = 0xa43,
	PN_MICROENABLE4AD4CL = 0xa42,
	PN_MICROENABLE4VD1CL = 0xa41,
	PN_MICROENABLE4FULLx1 = PN_MICROENABLE4VD1CL,
	PN_MICROENABLE4VD4CL = 0xa44,
	PN_MICROENABLE4FULLx4 = PN_MICROENABLE4VD4CL,
	PN_MICROENABLE4AS1CL = 0xa45,
	PN_MICROENABLE4_H264CLx1 = 0xb41,
	PN_MICROENABLE4VQ4GE = 0xe44,
	PN_MICROENABLE4GIGEx4 = PN_MICROENABLE4VQ4GE,
	PN_MICROENABLE4AQ4GE = 0xe42,
	
	PN_PX100 = 0xc41,
	PN_PX200 = 0xc42,

	PN_UNKNOWN = 0xffff,
	PN_NONE    = 0
};

#endif
