# Makefile for programs in this directory

CXX = g++

CODE_PATH = ./src1210
PCODIR = ./lib/pco_include
PCOLIBDIR = ./lib/pco_lib
CPCODIR = ./lib/pco_classes
SISOLIB = ./lib/siso_lib

C11FLAG += -std=c++0x
CFLAGS += -O -Wall -Wno-comments -DLINUX -I$(PCODIR) -I$(CPCODIR) -lrt  -lbiodaq -lm -pthread

CLSERLIB = $(SISOLIB)/libclserme4.so
FGLIB = $(SISOLIB)/libfglib5.so
 
DISPLIB = $(PCOLIBDIR)/libpcodisp.a
LOGLIB = $(PCOLIBDIR)/libpcolog.a
FILELIB = $(PCOLIBDIR)/libpcofile.a

HEADERS = $(PCODIR)/VersionNo.h $(CPCODIR)/Cpco_cl_com.h $(CPCODIR)/Cpco_me4.h $(CPCODIR)/Cpco_me4_GS.h

CPCOCLASS_SRC = Cpco_cl_com.cpp Cpco_me4.cpp reorder_func.cpp
CPCOCLASS = $(addprefix $(CPCODIR)/,$(CPCOCLASS_SRC) )

SOURCES = $(CODE_PATH)/*.cpp

TARGETS = main ctemp zguide zfind zstatus

FBOBJECTS =  fireball_camera2.o frameblob.o bloblist.o image_function.o guide_data.o guiding_settings.o message_data.o message_function.o staticAO.o image_function.o

all:    clean $(TARGETS)

clean:
		@echo "Cleaning make (safety reasons)..."
		@$(RM) *~ bin/$(TARGETS)  $(CPCODIR)/*~  *.log *.o
        
%.o: src1210/%.cpp
		@echo -n "Compiling1 "$<"..."
		@$(CXX) $(C11FLAG) $(CFLAGS)  $< -c
		@echo " Done1"
        
%.o: src1210/%.c
		@echo -n "Compiling2 "$<"..."
		@$(CC) $(CFLAGS) $< -c
		@echo " Done2"
    

main: src1210/main.cpp camera.o log.o fitswrapper.o gps.o sun.o $(FGLIB) $(CLSERLIB) $(CPCOCLASS) $(FILELIB) $(LOGLIB) $(HEADERS)
		@echo -n "Compiling MINT..."
		@mkdir -p -v ./bin
		@$(CXX) $(C11FLAG) $(CFLAGS) $? -o bin/mint -I./src1210/ $(FILELIB) $(LOGLIB) $(FGLIB) $(CLSERLIB) -lcfitsio
		@echo " Done4"

testcam:	src1210/testcam.cpp fireball_camera.o   $(FGLIB) $(CLSERLIB) $(CPCOCLASS) $(FILELIB) $(LOGLIB) $(HEADERS)
		@echo "Compiling testcam..."
		@$(CXX) $(C11FLAG) $(CFLAGS) $? -o bin/testcam -I./src1210/ $(FILELIB) $(LOGLIB) $(FGLIB) $(CLSERLIB) 


testcam2:	src1210/testcam2.cpp fireball_camera2.o frameblob.o bloblist.o image_analysis.o  $(FGLIB) $(CLSERLIB) $(CPCOCLASS) $(FILELIB) $(LOGLIB) $(HEADERS)
		@echo "Compiling testcam2..."


fbguider:      	./src1210/fbguider.cpp $(FBOBJECTS) $(FGLIB) $(CLSERLIB) $(CPCOCLASS) $(FILELIB) $(LOGLIB) $(HEADERS)
		@$(CXX) $(C11FLAG) $(CFLAGS) $? -o bin/fbguider -I./src1210/ $(FILELIB) $(LOGLIB) $(FGLIB) $(CLSERLIB) -lbiodaq -lrt

run:	clean main
		@echo "Running MINT..."
		@bash -l -c "if [ `pgrep mint | wc -l` -lt 2 ]; then ./bin/mint; else echo 'Instance already running!'; fi;"

run_testcam:	clean testcam
		@echo "Running testcam..."
		@bash -l -c "if [ `pgrep testcam | wc -l` -lt 2 ]; then ./bin/testcam; else echo 'Instance already running!'; fi;"

run_testcam2:	clean testcam2
		@echo "Running testcam2..."
		@bash -l -c "if [ `pgrep testcam2 | wc -l` -lt 2 ]; then ./bin/testcam2; else echo 'Instance already running!'; fi;"

run_all:
		@echo "Running all..."
		@bash -l -c "if [ `pgrep fbguider | wc -l` -lt 2 ]; then ./bin/fbguider; else echo 'Instance already running!'; fi;"
        
runfb:		clean fbguider
		@echo "Running fbguider.."
		@bash -l -c "if [ `pgrep fbguider | wc -l` -lt 2 ]; then ./bin/fbguider; else echo 'Instance already running!'; fi;"


install:clean all
		@echo "Installing MINT..."
		@mkdir -p /usr/rubble/bin/
		@cp bin/* /usr/rubble/bin/

