//DO NOT CHANGE THESE (UNLESS YOU CHANGE CAMERA)
#define FULL_WIDTH	2560
#define FULL_HEIGHT	2160



// YOU CAN CHANGE THESE
#define BIN_X		2
#define BIN_Y		2
#define PIXELRATE	286000000

#define DELAY		0
#define EXPOSURE	33

#define MAXSTARS	8
